version: '3.8'

services:
  mlflow:
    build:
      context: .
      dockerfile: ./code/mlflow.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data/mlflow:/home/mlflow/
      - ./secrets/mlflow:/run/secrets:ro
    networks:
      - app-network
  prefect:
    build:
      context: .
      dockerfile: ./code/prefect.dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./data/prefect:/database/
    networks:
      - app-network
  accident-injury-datasets-updater:
    build:
      context: .
      dockerfile: ./code/datasets_update/datasets_updater.dockerfile
    volumes:
      - ./data/datasets/:/datasets
    networks:
      - app-network
    restart: always
  accident-injury-model-trainer:
    build:
      context: .
      dockerfile: ./code/model_training/model_trainer.dockerfile
    volumes:
      - ./data/datasets/for_model:/datasets:ro
    networks:
      - app-network
    restart: always
  accident-injury-prediction-service:
    image: accident-injury-prediction-service:v1
    ports:
      - "9696:9696"
    volumes:
      - ./secrets/prediction_server:/run/secrets:ro
    env_file: served_model_env_vars
    restart: always
networks:
  app-network:
    driver: bridge